apiVersion: v1
kind: Service
metadata:
  name: math-api-service
spec:
  type: NodePort
  selector:
    app: math-api
  ports:
    - port: 80       # Service port
      targetPort: 5000  # Should match the port from the ConfigMap
      nodePort: 30000  # (Optional) The port on the node to expose externally, in the range 30000-32767
